//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ventas
    {
        public int id_venta { get; set; }
        public string rut_vendedor { get; set; }
        public Nullable<double> monto { get; set; }
        public int margen { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Tbl_Comision Tbl_Comision { get; set; }
        public virtual Tbl_Vendedor Tbl_Vendedor { get; set; }
    }
}
